name: .NET 8.0 CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-artifact: ${{ steps.build.outputs.artifact-path }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore ./Product.sln

    - name: Build the solution
      id: build
      run: |
        dotnet build ./Product.sln --no-restore --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore ./Product.sln

    - name: Run tests for Api.Implementation
      run: dotnet test ./Api.Implementation.Tests/Api.Implementation.Tests.csproj --no-build --configuration Release

    - name: Run tests for Business
      run: dotnet test ./Business.Tests/Business.Tests.csproj --no-build --configuration Release
